/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RevenueRecipientInterface extends Interface {
    getFunction(nameOrSignature: "attemptReentry" | "configure" | "marketplace" | "reentrySucceeded" | "register" | "rejectPayment" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attemptReentry', values?: undefined): string;
encodeFunctionData(functionFragment: 'configure', values: [boolean, boolean]): string;
encodeFunctionData(functionFragment: 'marketplace', values?: undefined): string;
encodeFunctionData(functionFragment: 'reentrySucceeded', values?: undefined): string;
encodeFunctionData(functionFragment: 'register', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectPayment', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attemptReentry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'configure', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reentrySucceeded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectPayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface RevenueRecipient extends BaseContract {
    
    connect(runner?: ContractRunner | null): RevenueRecipient;
    waitForDeployment(): Promise<this>;

    interface: RevenueRecipientInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attemptReentry: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    configure: TypedContractMethod<
      [reject: boolean, reenter: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    marketplace: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reentrySucceeded: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    register: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rejectPayment: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attemptReentry'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'configure'): TypedContractMethod<
      [reject: boolean, reenter: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketplace'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reentrySucceeded'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectPayment'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }