/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ModelChain {
      
    export type ModelStruct = {id: BigNumberish, owner: AddressLike, name: string, cid: string, modelHash: string, price: BigNumberish, royalty: BigNumberish, active: boolean}

    export type ModelStructOutput = [id: bigint, owner: string, name: string, cid: string, modelHash: string, price: bigint, royalty: bigint, active: boolean] & {id: bigint, owner: string, name: string, cid: string, modelHash: string, price: bigint, royalty: bigint, active: boolean }
  
    }

  export interface ModelChainInterface extends Interface {
    getFunction(nameOrSignature: "getModel" | "getModelCount" | "hasLicense" | "pendingWithdrawals" | "platform" | "purchaseLicense" | "registerModel" | "setModelActive" | "verifyModel" | "withdrawRevenue"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LicensePurchased" | "ModelRegistered" | "ModelStatusChanged" | "RevenueWithdrawn" | "RoyaltyPaid"): EventFragment;

    encodeFunctionData(functionFragment: 'getModel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getModelCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasLicense', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'pendingWithdrawals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'platform', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchaseLicense', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerModel', values: [string, string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setModelActive', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'verifyModel', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'withdrawRevenue', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getModel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModelCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasLicense', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platform', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchaseLicense', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerModel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setModelActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyModel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRevenue', data: BytesLike): Result;
  }

  
    export namespace LicensePurchasedEvent {
      export type InputTuple = [modelId: BigNumberish, buyer: AddressLike, price: BigNumberish];
      export type OutputTuple = [modelId: bigint, buyer: string, price: bigint];
      export interface OutputObject {modelId: bigint, buyer: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModelRegisteredEvent {
      export type InputTuple = [modelId: BigNumberish, owner: AddressLike, name: string, cid: string, price: BigNumberish];
      export type OutputTuple = [modelId: bigint, owner: string, name: string, cid: string, price: bigint];
      export interface OutputObject {modelId: bigint, owner: string, name: string, cid: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModelStatusChangedEvent {
      export type InputTuple = [modelId: BigNumberish, active: boolean];
      export type OutputTuple = [modelId: bigint, active: boolean];
      export interface OutputObject {modelId: bigint, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevenueWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint];
      export interface OutputObject {recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoyaltyPaidEvent {
      export type InputTuple = [modelId: BigNumberish, owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [modelId: bigint, owner: string, amount: bigint];
      export interface OutputObject {modelId: bigint, owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ModelChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): ModelChain;
    waitForDeployment(): Promise<this>;

    interface: ModelChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getModel: TypedContractMethod<
      [modelId: BigNumberish, ],
      [ModelChain.ModelStructOutput],
      'view'
    >
    

    
    getModelCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hasLicense: TypedContractMethod<
      [modelId: BigNumberish, buyer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pendingWithdrawals: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    platform: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    purchaseLicense: TypedContractMethod<
      [modelId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    registerModel: TypedContractMethod<
      [name: string, cid: string, modelHash: string, price: BigNumberish, royalty: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    setModelActive: TypedContractMethod<
      [modelId: BigNumberish, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    verifyModel: TypedContractMethod<
      [modelId: BigNumberish, submittedHash: string, ],
      [boolean],
      'view'
    >
    

    
    withdrawRevenue: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getModel'): TypedContractMethod<
      [modelId: BigNumberish, ],
      [ModelChain.ModelStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getModelCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasLicense'): TypedContractMethod<
      [modelId: BigNumberish, buyer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingWithdrawals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'platform'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'purchaseLicense'): TypedContractMethod<
      [modelId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'registerModel'): TypedContractMethod<
      [name: string, cid: string, modelHash: string, price: BigNumberish, royalty: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setModelActive'): TypedContractMethod<
      [modelId: BigNumberish, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyModel'): TypedContractMethod<
      [modelId: BigNumberish, submittedHash: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawRevenue'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LicensePurchased'): TypedContractEvent<LicensePurchasedEvent.InputTuple, LicensePurchasedEvent.OutputTuple, LicensePurchasedEvent.OutputObject>;
getEvent(key: 'ModelRegistered'): TypedContractEvent<ModelRegisteredEvent.InputTuple, ModelRegisteredEvent.OutputTuple, ModelRegisteredEvent.OutputObject>;
getEvent(key: 'ModelStatusChanged'): TypedContractEvent<ModelStatusChangedEvent.InputTuple, ModelStatusChangedEvent.OutputTuple, ModelStatusChangedEvent.OutputObject>;
getEvent(key: 'RevenueWithdrawn'): TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
getEvent(key: 'RoyaltyPaid'): TypedContractEvent<RoyaltyPaidEvent.InputTuple, RoyaltyPaidEvent.OutputTuple, RoyaltyPaidEvent.OutputObject>;

    filters: {
      
      'LicensePurchased(uint256,address,uint256)': TypedContractEvent<LicensePurchasedEvent.InputTuple, LicensePurchasedEvent.OutputTuple, LicensePurchasedEvent.OutputObject>;
      LicensePurchased: TypedContractEvent<LicensePurchasedEvent.InputTuple, LicensePurchasedEvent.OutputTuple, LicensePurchasedEvent.OutputObject>;
    

      'ModelRegistered(uint256,address,string,string,uint256)': TypedContractEvent<ModelRegisteredEvent.InputTuple, ModelRegisteredEvent.OutputTuple, ModelRegisteredEvent.OutputObject>;
      ModelRegistered: TypedContractEvent<ModelRegisteredEvent.InputTuple, ModelRegisteredEvent.OutputTuple, ModelRegisteredEvent.OutputObject>;
    

      'ModelStatusChanged(uint256,bool)': TypedContractEvent<ModelStatusChangedEvent.InputTuple, ModelStatusChangedEvent.OutputTuple, ModelStatusChangedEvent.OutputObject>;
      ModelStatusChanged: TypedContractEvent<ModelStatusChangedEvent.InputTuple, ModelStatusChangedEvent.OutputTuple, ModelStatusChangedEvent.OutputObject>;
    

      'RevenueWithdrawn(address,uint256)': TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
      RevenueWithdrawn: TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
    

      'RoyaltyPaid(uint256,address,uint256)': TypedContractEvent<RoyaltyPaidEvent.InputTuple, RoyaltyPaidEvent.OutputTuple, RoyaltyPaidEvent.OutputObject>;
      RoyaltyPaid: TypedContractEvent<RoyaltyPaidEvent.InputTuple, RoyaltyPaidEvent.OutputTuple, RoyaltyPaidEvent.OutputObject>;
    
    };
  }